module.exports = {

  // Authentication (defaults for development)
  AUTHENTICATION_ENABLED: process.env.WMT_WEB_AUTHENTICATION_ENABLED || false,
  ACTIVE_DIRECTORY_ENTRY_POINT: process.env.WMT_ACTIVE_DIRECTORY_ENTRY_POINT || 'enter here', // SAML-P Sign-On Endpoint
  ACTIVE_DIRECTORY_ISSUER: process.env.WMT_ACTIVE_DIRECTORY_ISSUER || 'app id', // APP-ID
  ACTIVE_DIRECTORY_RETURN_ADDRESS: process.env.WMT_ACTIVE_DIRECTORY_RETURN_ADDRESS || '/login',
  ACTIVE_DIRECTORY_DOMAIN: process.env.WMT_ACTIVE_DIRECTORY_DOMAIN || 'wmtnonproduction.onmicrosoft.com', // SAML CERT

  // Session and Cookie security (defaults for development)
  APPLICATION_SECRET: process.env.WMT_WEB_APPLICATION_SECRET, // NO DEFAULT FOR SECURITY REASONS, WILL FAIL IF NOT SET
  SECURE_COOKIE: process.env.WMT_WEB_SECURE_COOKIE || 'false',
  SESSION_COOKIE_MAXAGE: process.env.WMT_WEB_SESSION_COOKIE_MAXAGE || '3600000', // 60 min default
  RESAVE_SESSION: process.env.WMT_WEB_SESSION_COOKIE_RESAVE || 'true',
  SAVE_UNINITIALIZED_SESSION: process.env.WMT_WEB_SESSION_COOKIE_SAVE_UNINITIALISED || 'false',

  // DB
  LIVE_DATABASE_SERVER: process.env.WMT_LIVE_DB_SERVER || 'localhost',
  LIVE_DATABASE: process.env.WMT_LIVE_DB_NAME || 'postgres',
  LIVE_DATABASE_USERNAME: process.env.WMT_LIVE_DB_USERNAME || 'root',
  LIVE_DATABASE_PASSWORD: process.env.WMT_LIVE_DB_PASSWORD || 'dev',

  HISTORY_DATABASE_SERVER: process.env.WMT_HISTORY_DB_SERVER || 'localhost',
  HISTORY_DATABASE: process.env.WMT_HISTORY_DB_NAME || 'postgres',
  HISTORY_DATABASE_USERNAME: process.env.WMT_HISTORY_DB_USERNAME || 'root',
  HISTORY_DATABASE_PASSWORD: process.env.WMT_HISTORY_DB_PASSWORD || 'dev',

  ARCHIVE_DATA_LIMIT: '1000000',

  ARCHIVE_DATABASE_START_DATE: process.env.WMT_ARCHIVE_DATABASE_START_DATE || '26/08/2016',

  CURRENT_DATABASE_START_DATE: process.env.WMT_CURRENT_DATABASE_START_DATE || '07/05/2021',

  NUMBER_OF_DASHBOARD_FILES: 10,

  ARMS_COMMUNITY_MULTIPLIER: 1,
  ARMS_LICENCE_MULTIPLIER: 1,

  LEGACY_MAX_WORKLOAD_REPORT_ID: process.env.WMT_LEGACY_MAX_WORKLOAD_REPORT_ID || '639',
  ARCHIVE_MAX_WORKLOAD_REPORT_ID: process.env.WMT_ARCHIVE_MAX_WORKLOAD_REPORT_ID || '1284',

  LEGACY_MAX_WORKLOAD_ID: process.env.WMT_LEGACY_MAX_WORKLOAD_ID || '2540621',
  ARCHIVE_MAX_WORKLOAD_ID: process.env.WMT_ARCHIVE_MAX_WORKLOAD_ID || '5313915'
}
