module.exports = {
    // This filename is relative to the nunjucks directories (configured elsewhere).
    // From nunjucks node_loaders.getSource: "Only allow the current directory [anything in the above path] and anything underneath it to be searched"
    njkName: 'search-for-officer.njk',
    njkData: {
        surname: 'Example name',
        results: [
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Zith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Yith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
          {
            region: 'Region 1',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Pith',
            workloadOwnerId: 12,
          },
          {
            region: 'Region 2',
            ldu: 'Ldu 2',
            team: 'Team 2',
            surname: 'Smith',
            forename: 'Lith',
            workloadOwnerId: 13,
          },
          {
            region: 'Region 3',
            ldu: 'Ldu 1',
            team: 'Team 1',
            surname: 'Smith',
            forename: 'Tith',
            workloadOwnerId: 14,
          },
        ],
    }
}
