---
# Per environment values which override defaults in hmpps-template-typescript/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-workload-web-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-workload-web-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-tier

