---
generic-service:

  ingress:
    className: modsec-non-prod
    host: workload-measurement-dev.hmpps.service.justice.gov.uk
  env:
    INGRESS_URL: "https://workload-measurement-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    MANAGE_USERS_SERVICE_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    WORKFORCE_ALLOCATIONS_URL: "https://workforce-management-dev.hmpps.service.justice.gov.uk"
    ALLOCATIONS_SERVICE_URL: "https://hmpps-allocations-dev.hmpps.service.justice.gov.uk"
    USER_PREFERENCE_SERVICE_URL: "https://hmpps-user-preferences-dev.hmpps.service.justice.gov.uk"
  
  scheduledDowntime:
    enabled: true

# Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
generic-prometheus-alerts:
  businessHoursOnly: true