---
generic-service:
  replicaCount: 2

  ingress:
    host: workload-measurement-dev.hmpps.service.justice.gov.uk
  env:
    INGRESS_URL: "https://workload-measurement-dev.hmpps.service.justice.gov.uk"

