---
generic-service:

  ingress:
    host: workload-measurement-dev.hmpps.service.justice.gov.uk
  env:
    INGRESS_URL: "https://workload-measurement-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    WORKFORCE_ALLOCATIONS_URL: "https://workforce-management-dev.hmpps.service.justice.gov.uk"

