name: Build and test node

on:
  workflow_call:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"

permissions:
  contents: read

jobs:
  node-unit-test:
    name: Run the node unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js (${{ inputs.node_version_file }})
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}
          cache: npm

      # Install deps including devDependencies (so mocha is available)
      - name: Install dependencies
        run: npm ci --include=dev
        env:
          NODE_ENV: development

      - name: unit tests
        id: unit-tests
        run: npm run test:ci

      - name: upload the artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm_unit_test_artifacts
          path: |
            test_results
          if-no-files-found: ignore

      - name: publish test report
        if: ${{ !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@v2
        with:
          artifact: npm_unit_test_artifacts
          name: Test Report
          path: |
            test_results/**/*.xml
            **/junit*.xml
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: failed
          list-tests: failed

      - name: fail the action if the tests failed
        if: ${{ steps.unit-tests.outcome == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed('Unit tests failed')
