name: Pipeline [test -> build -> deploy]

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: false
        type: boolean

# Default token perms for all jobs in this workflow
permissions:
  contents: read
  packages: write
  actions: read    # needed to list/download artifacts in this run

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  node_build:
    name: node build
    # Let the called workflow upload artifacts
    permissions:
      contents: read
      actions: write
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@v2
    secrets: inherit

  # --- OPTIONAL: Consumer job to prove & use the build artifacts from this SAME run ---
  use_built_assets:
    name: Use npm build artifacts
    needs: node_build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: List artifacts in this run (debug)
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts --jq '.artifacts[].name'

      # broad download to inspect everything; delete after you confirm the exact name you want
      - name: Download all artifacts (debug)
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts_all
      - run: ls -R ./artifacts_all || true

      # precise download — what you actually want to keep
      - name: Download npm build artifacts (exact)
        uses: actions/download-artifact@v5
        with:
          name: npm_build_artifacts
          path: ./artifacts
      - run: ls -lah ./artifacts || true

      # (Alternative) if you prefer a pattern:
      # - uses: actions/download-artifact@v5
      #   with:
      #     pattern: npm_*_artifacts
      #     merge-multiple: true
      #     path: ./artifacts

  node_unit_tests:
    name: node unit tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_unit_tests.yml@v2
    needs: [node_build]
    secrets: inherit

  node_integration_tests:
    name: node integration tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_integration_tests.yml@v2
    needs: [node_build]
    secrets: inherit

  helm_lint:
    strategy:
      matrix:
        environments: ['dev', 'preprod', 'prod']
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}

  build:
    name: Build docker image from hmpps-github-actions
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    needs:
      - node_integration_tests
      - node_unit_tests
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: false

  deploy_dev:
    name: Deploy to the dev environment
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'dev'
      app_version: '${{ needs.build.outputs.app_version }}'
      helm_timeout: '5m'

  deploy_preprod:
    name: Deploy to the preprod environment
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'
      helm_timeout: '5m'

  deploy_prod:
    name: Deploy to the prod environment
    needs:
      - build
      - helm_lint
      - deploy_preprod
      - deploy_dev
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.build.outputs.app_version }}'
      helm_timeout: '5m'
